### ISSUE TITLE
Exception in Android

### ISSUE THREAD

**Issue by Dcodechef** [conekta/conekta-java#3]
Hi,

I wanted to use this library in Android for payment. Unfortunately I am facing few issues:

java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

I am using ConektaJava.jar and json.jar.

   Conekta.setApiKey(conekta_pv_key);
        JSONObject valid_payment_method;
        JSONObject valid_visa_card;
        try {
            valid_visa_card = new JSONObject("{'card':'4242424242424242'}");
            valid_payment_method = new JSONObject("{'description':'Stogies'," +
                    "'reference_id':'9839-wolf_pack'," +
                    "'amount':20000," +
                    "'currency':'MXN'}");
            JSONObject params = valid_payment_method.put("card", valid_visa_card.get("card"));
            try {
                Charge charge = Charge.create(params);
            } catch (Error e) {
                System.out.println(e.toString());
            }
        } catch (JSONException je) {

        }

what is wrong in this Or how shell I implement this   in Android (Procedure) ?

Regards,
Deep

**Comment by MauricioMurga** [comment]
@Dcodechef, this library uses javax.net.ssl.SSLContext and javax.net.ssl.TrustManagerFactory. Is it possible that you use these instead of OpenSSLX509CertificateFactory?

**Comment by Dcodechef** [comment]
@MauricioMurga Yes, I can use then mentioned ssl.
The thing is how can I use them with conekta-java library ?

Regards,
Deep

**Comment by Dcodechef** [comment]
@MauricioMurga I tired to fix the SSL issue, now using certificate from: https://www.washington.edu/itconnect/security/ca/load-der.crt

Charge charge = Charge.create(params); //Here I am getting following exception
Could not connect to https://api.conekta.io

Any help would be highly appreciated.

**Comment by MauricioMurga** [comment]
@Dcodechef, could you try to connect to another website that does not have ssl such as http://example.com/ and confirm that in fact is an issue of ssl?

Thanks,

**Comment by Faxterol** [comment]
Tengo el mismo problema, estoy usando parse y conekta.. con parse no tengo problemas pero conekta me muestra el mismo error que cita @Dcodechef ayuda porfavor!

**Comment by MauricioMurga** [comment]
Hi @Dcodechef, @Faxterol, you should be using the tokenizer aar that has a patch for this exception.

https://github.com/conekta/conekta-android/blob/master/app/libs/tokenizer-release.aar

The aar uses a patched version of ConektaJava library designed for android exclusively:

https://github.com/conekta/conekta-android/blob/6e7e9a789c3515847204da49d0a9cb4271804386/app/libs/ConektaJava.jar

**Comment by darkon76** [comment]
Hello, Im currently using the ConektaJava.jar from git, that is the same inside tokenizer-release.aar, 

I have the same problem as  @Dcodechef, @Faxterol

My code. 
LOG.i(TAG,"Conektapago");
		Conekta.setApiKey("1tv5yJp3xnVZ7eK67m4h");
		JSONObject valid_payment_method;
		JSONObject valid_visa_card;
		try {
			valid_visa_card = new JSONObject("{'card':'tok_test_visa_4242'}");
		
		valid_payment_method = new JSONObject("{'description':'Stogies'," +
		  "'reference_id':'9839-wolf_pack'," +
		  "'amount':20000," +
		  "'currency':'MXN'}");
		JSONObject params = valid_payment_method.put("card", valid_visa_card.get("card"));
		try {
			  Charge charge = null;
			try {
				charge = Charge.create(params);
				LOG.i(TAG,"Charge" + charge.toString());
			} catch (com.conekta.Error e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			  
			  
			} catch(Error e) {
			  System.out.println(e.toString());
			}
		} catch (JSONException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}


my log

06-09 18:22:09.578: I/ConektaPago(9484): Conektapago
06-09 18:22:09.726: I/System.out(9484): java.security.cert.CertificateException: org.apache.harmony.xnet.provider.jsse.OpenSSLX509CertificateFactory$ParsingException: org.apache.harmony.xnet.provider.jsse.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
06-09 18:22:09.726: W/System.err(9484): Could not connect to https://api.conekta.io
06-09 18:22:09.730: W/System.err(9484): 	at com.conekta.Requestor.request(Requestor.java:114)
06-09 18:22:09.730: W/System.err(9484): 	at com.conekta.Resource.scpCreate(Resource.java:65)
06-09 18:22:09.730: W/System.err(9484): 	at com.conekta.Charge.create(Charge.java:55)

**Comment by MauricioMurga** [comment]
Hi @darkon76, are you using this ConektaJava version?
https://github.com/conekta/conekta-android/blob/6e7e9a789c3515847204da49d0a9cb4271804386/app/libs/ConektaJava.jar

As I stated, ConektaJava for mobile has a patch in conekta-android repository.

Let me know if you are using this version.

**Comment by darkon76** [comment]
Thats the one that Im using. 

Also extracting the .aar, I found another ConektaJava that is the same as  app/libs/ConektaJava.

Regards,

**Comment by MauricioMurga** [comment]
Sorry @darkon76, I was a bit confused since the issue is posted here and not in conekta-android repository. The AAR has everything you need to tokenize cards and to process payments. There is no need to use a ConektaJava besides the one that has already the artifact.

It seems that when using mobiles there is an issue with certificates providers and the AAR has a patch for this issue.

If you can tokenize a card, there should be no problem when creating a charge.

**Comment by ChelixPreciado** [comment]
Did someone resolve this problem? I am having the same issue.

java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
Could not connect to https://api.conekta.io

**Comment by MauricioMurga** [comment]
Hi @ChelixPreciado, what version of conekta-android are you using?

**Comment by MauricioMurga** [comment]
Hi @ChelixPreciado, @darkon76, @Dcodechef, @Faxterol. I've made an update to the certificates, it seems that comments and titles can cause exceptions sometimes. I also added some comments in the README section:

If you cannot connect to https://api.conekta.io, try installing the certificate in your java environment:
```
keytool -import -noprompt -trustcacerts -alias conekta -file %PROJECT_PATH%\ssl_data\ca_bundle.pem -keystore %JAVA_HOME%\lib\security\cacerts -storepass changeit
```

R

**Comment by eduardoconekta** [comment]
Debugging the same issue, there is a variant when you change the url of your request,  like my  

> customer/cus_id/etc

 the first slash may broke your request if you dont put it 

> api.com**customer/cus_id/etc***


for me it works: 

>api.com/customer/cus_id/etc
