### ISSUE TITLE
Could not connect to https://api.conekta.io.

### ISSUE THREAD

**Issue by antoniomadrigal10** [conekta/conekta-java#40]
Hello, i doing everything as you guys said on the documentation and still getting the same error!

import the certificate just like this

sudo keytool -import -noprompt -trustcacerts -alias conekta -file ssl_data/ca_bundle.pem -keystore /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/security/cacerts -storepass changeit

Result: Certificate was added to keystore

But still can't make it work

03-08 17:31:34.826 32719-32719/? I/InstantRun: Starting Instant Run Server for com.berea
03-08 17:31:35.028 32719-32719/? W/System.err: Could not connect to https://api.conekta.io.
03-08 17:31:35.028 32719-32719/? W/System.err:     at io.conekta.Requestor.request(Requestor.java:119)
03-08 17:31:35.028 32719-32719/? W/System.err:     at io.conekta.Resource.scpCreate(Resource.java:65)
03-08 17:31:35.028 32719-32719/? W/System.err:     at io.conekta.Customer.create(Customer.java:94)
03-08 17:31:35.028 32719-32719/? W/System.err:     at com.berea.SplashScreen.onCreate(SplashScreen.java:49)

Any help please!

Thanks

**Comment by eduardoconekta** [comment]
Is there fixed for you  @antoniomadrigal10  or you are still having this issue ?

**Comment by eduardoconekta** [comment]
please create a gist with your code to get more information about how to reproduce your problem @antoniomadrigal10 thanks!

**Comment by eduardoconekta** [comment]
this error is commonly because your application can't reach conekta api, and this error is also build from the lib side no from api side.

**Comment by jaime-md** [comment]
I'm also getting this error. Not getting the order recieved screen.
What's the way to solve this?

I'm currently running in a local MAMP server, with a custom-made SSL certificate.

My environment:
Wordpress 4.98
WooCommerce 3.4.4
Conekta Payment Gateway 3.0.4

After getting error, orders are created in WP admin as "pendiente de pago", and logs in Conekta admin appear with 200 status.

Help please. Thanks.

**Comment by aleph79** [comment]
Hello
I'm using the java library, and if he lets me connect, but after a few minutes he does not let me make another request, he marks me an error in the file io.conekta.Requestor after the next instruction
try {
            os = connection.getOutputStream ();
this is the error appears, Connection reset
 can you help me?
![Captura de Pantalla 2019-04-24 a la(s) 18 49 42](https://user-images.githubusercontent.com/8138924/56700814-bef59e80-66c1-11e9-94dc-f4ce71610db2.png)
