### ISSUE TITLE
Error en documentación

### ISSUE THREAD

**Issue by rvargas** [conekta/conekta-java#41]
Hola, 

En la [documentación](https://developers.conekta.com/api?language=java#create-payment-source), se hace uso del método `createSource`, sin embargo, el código tiene el método [`createPaymentSource`](https://github.com/conekta/conekta-java/blob/master/src/io/conekta/Customer.java#L128).

Saludos.

**Comment by rvargas** [comment]
Parece que encontré otra discrepancia.

En la [documentación](https://developers.conekta.com/api?language=java#payment-source-object) se muestran los atributos del objeto `PaymentSource`, pero en el [código](https://github.com/conekta/conekta-java/blob/master/src/io/conekta/PaymentSource.java#L12), no vienen exactamente todos esos atributos, como lo son, por ejemplo, `brand` y `last4`, así que no se pueden acceder a ellos.

Ejecutando el ejemplo `System.out.println(payment_source.toString());` despues de crear un `customer` con un `paymentSource` obtengo:

```
{id=src_2gL45s1NXGBLbtX7v, exp_month=12, exp_year=19, name=Jorge Lopez, type=card}
```

**Comment by eduardoconekta** [comment]
Los dos issues ya quedaro nresultos @rvargas  (: Gracias por tu contribución
