### ISSUE TITLE
Error al recuperar los params 

### ISSUE THREAD

**Issue by david-otero** [conekta/conekta-java#66]
Hola:

He observado que el campo 'param' del error no se está recuperando correctamente del JSON de respuesta. Por lo que visto la clase _Error_ tiene un constructor a partir del JSON en el que se obtiene el valor del _param_ (línea 48):

`        String param = error.optString("param", "");` 

Pero luego esa variable no se asigna al campo _params_ de la clase, en su lugar se vuelve a asignar el propio _params_ (línea 69). 

`        this.params = params;` 

Creo que quitando la ‘s’ del final se resolvería el problema.

Un saludo.

**Comment by eduardoconekta** [comment]
Gracias @david-otero, tienes un flujo en el que notes ese comportamiento, para que nosotros podamos reproducir el caso ?

**Comment by david-otero** [comment]
Hola:

Tengo un caso de prueba en el que intento realizar un pago pero enviando datos erróneos del comprador (en mi caso envío el nombre en blanco y el email y el teléfono con un formato incorrecto). En la respuesta de conekta se lanza una excepción de tipo ErrorList con tres objetos Error en detail. En estos objetos los campos message y debug_message están rellenos y presentan el mensaje correcto (el esperado por el error en el campo) pero el campo param siempre está vacío.

Si acceso a la web para comprobar la respuesta ante la petición que acabo de realizar veo que en el JSON el campo param sí que está relleno, por lo que parece un problema de la librería al transformar la respuesta JSON a un objeto Java.

Un saludo.

De: Eduardo Enriquez [mailto:notifications@github.com]
Enviado el: miércoles, 20 de septiembre de 2017 17:27
Para: conekta/conekta-java <conekta-java@noreply.github.com>
CC: David Otero Cabero <david.otero@connectis-ict.es>; Mention <mention@noreply.github.com>
Asunto: Re: [conekta/conekta-java] Error al recuperar los params (#66)


Gracias @david-otero<https://github.com/david-otero>, tienes un flujo en el que notes ese comportamiento, para que nosotros podamos reproducir el caso ?

**Comment by eduardoconekta** [comment]
ok @david-otero lo revisaremos, tan pronto nos sea posible para hacer el release de este bug, el tiempo estimado entre cada release es de 2 semanas aproximadamente gracias, te avisaremos cuando salga esta nueva version

**Comment by david-otero** [comment]
Hola:

¿Habéis tenido oportunidad de mirar este tema?

Un saludo.

**Comment by eduardoconekta** [comment]
@david-otero  hola una disculpa por la demora, no habíamos tenido tiempo, muchas gracias por hacer el debuggeo tan exacto y si tienes toda la razón eso fue un tipo de nuestro lado, estoy por hacer  el pull request tan pronto lo liberemos a maven te confirmamos

**Comment by david-otero** [comment]
Genial, quedo a la espera de la nueva versión.

Un saludo.

**Comment by eduardoconekta** [comment]
@david-otero esta version ya tiene cerca de 1 mes actualizada en maven, cierro el issue :)
