### ISSUE TITLE
Call Order Error

### ISSUE THREAD

**Issue by channgli** [conekta/conekta-java#69]
Hi ,
I use the test key to call the order api and call failed,Just order api failed. Can help to see why i my "amount": 3, it still happen.

Request  body:
![image](https://user-images.githubusercontent.com/29981166/30814993-5c243534-a244-11e7-84c8-4f976b71eef8.png)
Response body:
![image](https://user-images.githubusercontent.com/29981166/30815012-6cc54e5a-a244-11e7-8e39-09f8aca07a55.png)

if i use large amount ,it give me other error:
![image](https://user-images.githubusercontent.com/29981166/30815514-0b5b7f5c-a246-11e7-87e8-a3e304545318.png)

![image](https://user-images.githubusercontent.com/29981166/30815534-1bbfbbc4-a246-11e7-914f-62aceae1b3d3.png)

![image](https://user-images.githubusercontent.com/29981166/30814938-30b7ff98-a244-11e7-8b2a-d0a05b0f1ce4.png)

Best Regards,
Channing

**Comment by lu1s** [comment]
@channgli the amount needs to be in cents. Eg, 250 mexican pesos would be 25000.

**Comment by channgli** [comment]
@lu1s can you give me the example of the request ?

**Comment by lu1s** [comment]
@channgli This would be a correct request body for an order creation with charge:
```
{
  "line_items": [
    {
      "antifraud_info": {},
      "brand": "Consequatur soluta corrupti vero incidunt sapiente suscipit porro.",
      "description": "Autem eaque nulla quo iure facere eligendi id dicta.",
      "name": "Bernardo Tirado Ponce",
      "quantity": 2,
      "sku": "2cjgw4cyn3",
      "tags": [
        "Grocery",
        "Electronics",
        "Clothing"
      ],
      "unit_price": 1500
    }
  ],
  "shipping_lines": [
    {
      "amount": 1500,
      "carrier": "8msqtma7pd",
      "method": "xuo5umtx5s",
      "tracking_number": "bak7pn8s37"
    }
  ],
  "tax_lines": [
    {
      "amount": 1500,
      "description": "Ipsa amet qui cum."
    }
  ],
  "discount_lines": [
    {
      "amount": 1500,
      "code": "Et ut impedit aut ipsam laboriosam.",
      "type": "campaign"
    }
  ],
  "currency": "mxn",
  "customer_info": {
    "customer_id": "cus_2hH9VMRcCQKPHPfe4"
  },
  "shipping_contact": {
    "address": {
      "city": "Red Deer",
      "country": "AS",
      "residential": true,
      "state": "Alberta",
      "street1": "Alexis St",
      "street2": "250",
      "postal_code": "72894"
    },
    "between_streets": "Kurt Gödel, David Hilbert, Wilhelm Ackermann",
    "phone": "+1-202-555-0142",
    "receiver": "Olivia Merino Heredia"
  },
  "fiscal_entity": {
    "address": {
      "city": "Red Deer",
      "country": "cm",
      "external_number": "12",
      "internal_number": "10",
      "state": "Alberta",
      "street1": "Alexis St",
      "street2": "Something 250",
      "street3": null,
      "postal_code": "56401"
    },
    "tax_id": "CEO100524DX1",
    "name": "Rojas, Bustamante y Prieto Asociados"
  },
  "capture": true
}
```

**Comment by channgli** [comment]
Hi @lu1s ,
I use your request, it still exist this issue. see below:

![image](https://user-images.githubusercontent.com/29981166/30923936-d9de92f2-a3df-11e7-98bd-114d0ab53f12.png)

**Comment by lu1s** [comment]
#70
