### ISSUE TITLE
Wrong method call on Event object

### ISSUE THREAD

**Issue by pedroxs** [conekta/conekta-java#79]
The response JSON from your API is a Object and not an Array, I believe that on those two cases the correct method would be `io.conekta.Resource#scpWhereList` instead. 

https://github.com/conekta/conekta-java/blob/c6f088188063ee70f66b77899b92bde2f94dea2c/src/io/conekta/Event.java#L26

https://github.com/conekta/conekta-java/blob/c6f088188063ee70f66b77899b92bde2f94dea2c/src/io/conekta/Event.java#L26

**Comment by matiasrosemberg** [comment]
This project is now deprecated; you can use the newer one: https://github.com/conekta/ct-conekta-java
