### ISSUE TITLE
Error amount

### ISSUE THREAD

**Issue by cesar-regio** [conekta/conekta-java#83]
Cuando un cliente aplica un descuento a la compra y hace clic en finalizar compra, sale un mensaje de error que dice Error Amount: tiene un tipo inválido. Ya hablé con el equipo de soporte de Conekta y me comentan que es debido a que el plugin tiene que mandar la cantidad como un integro. Esta funcionalidad la debería de hacer el plugin, no se tendría porque modificar sus funciones del core.

Hice una modificación en los archivos relacionados a los correos electrónicos, pero no veo relación con el error. Considero que el error se debe a que el plugin no es compatible con la última versión de WordPress ¿Existe una nueva versión del plugin para WP 5.1.1? ¿Hay forma de solucionar el error?

**Comment by patadejaguar** [comment]
Debes enviar un entero como tal, si vas a enviar 2,999.26 debes enviar 299926, multiplica a 100 y lo envías como entero. Si tienes que forzar el tipo hazlo, el json acepta {'amount':299926} como tal.

**Comment by cesar-regio** [comment]
¿Pero no afectaría a algo más? Sucede que cuando hablé con CONEKTA me dijeron que no recomendaban modificar las funciones del plugin. Espero que el equipo de desarrollo de CONKETA se anime a actualizar, ya está la versión 5 y el plugin sigue en la 3.

**Comment by matiasrosemberg** [comment]
This project is now deprecated; you can use the newer one: https://github.com/conekta/ct-conekta-java
