### ISSUE TITLE
Could not connect to https://api.conekta.io java

### ISSUE THREAD

**Issue by aleph79** [conekta/conekta-java#85]
Hello
I'm using the java library, and if he lets me connect, but after a few minutes he does not let me make another request, he marks me an error in the file io.conekta.Requestor after the next instruction
try {
            os = connection.getOutputStream ();
this is the error appears, Connection reset
can you help me?
![Captura de Pantalla 2019-04-24 a la(s) 18 49 42](https://user-images.githubusercontent.com/8138924/56700969-899d8080-66c2-11e9-9c1a-0ba0a781023d.png)

**Comment by matiasrosemberg** [comment]
This project is now deprecated; you can use the newer one: https://github.com/conekta/ct-conekta-java
