### ISSUE TITLE
Plan update no existe 

### ISSUE THREAD

**Issue by lmurillo1204** [conekta/conekta-java#87]

**Comment by JohnMikeKS** [comment]
Isn't exists a solution for this yet?

**Comment by silvaGarduno** [comment]
Hello, a new library is being worked on to solve these problems.

**Comment by lmurillo1204** [comment]
> Hello, a new library is being worked on to solve these problems.

Ya se resolvio este problema?

**Comment by matiasrosemberg** [comment]
This project is now deprecated; you can use the newer one: https://github.com/conekta/ct-conekta-java
