### ISSUE TITLE
¿Que versión del SDK es la correcta?

### ISSUE THREAD

**Issue by hectorespert** [conekta/conekta-java#88]
En la documentación del SDK la ultima version es la `io.conekta:conekta-java:2.1.5` publicada el 2017, pero en el [buscador de Maven](https://search.maven.org/search?q=conekta-java) aparece otro SDK, `com.conekta.library-java:conekta-java:2.2.1` publicado en Mayo de 2019. 

<img width="901" alt="Screenshot 2019-08-08 at 17 14 23" src="https://user-images.githubusercontent.com/4323228/62715251-6ba12500-ba00-11e9-8c37-fc2d7e5b16d5.png">
 ¿Que versión del SDK es la correcta y en que se diferencian los dos SDK?

**Comment by fruizg0302** [comment]
La 2.2.1 es la más reciente, el cambio en la documentación lo publicaremos hoy por la tarde ó bien a más tardar mañana. @blackleg

**Comment by blackleg** [comment]
El código de esté repositorio también se va a actualizar?

**Comment by fruizg0302** [comment]
Es correcto

**Comment by blackleg** [comment]
¿La nueva version contiene estos cambios? https://github.com/conekta/conekta-java/pull/78

**Comment by fruizg0302** [comment]
Sí, procedo a cerrar el issue porque no hay tal.

**Comment by fruizg0302** [comment]
@blackleg BTW, hoy publicamos en este repositorio el version bump.

**Comment by blackleg** [comment]
@fruizg0302 Alguna novedad con la publicación?

**Comment by fruizg0302** [comment]
@blackleg Hola! sí también vamos a actualizar la documentación para que todo haga sentido. Lamento el retraso hoy integramos todo :D

**Comment by blackleg** [comment]
Gracias @fruizg0302, Quedo a la espera de la actualización de la documentación y del código.

**Comment by fruizg0302** [comment]
@blackleg Version Bump terminado en este repositorio, la documentación se liberará en un par de horas más, pero ya puedes empezar a trabajar. Saludos

**Comment by blackleg** [comment]
Gracias @fruizg0302

**Comment by blackleg** [comment]
@fruizg0302 @mariounderwood  He estado revisando el código fuente publicado para preparar este pull request: https://github.com/conekta/conekta-java/pull/91. En el version bump que se ha publicado, solo afecta al Readme, no se actualiza el código fuente. ¿El código fuente se va a mantener actualizado o solo se va a mantener la documentación?

**Comment by fruizg0302** [comment]
@blackleg Hola! El README estaba outdated, el código que ves actualmente es el que está publicado en Maven con la versión 2.2.1 y en temas de código incluye tu cambio del PR #78, entonces vamos a revisar el #91 y si todo va bien te avisamos cuando lo propaguemos a Maven ¿Qué te parece?

**Comment by blackleg** [comment]
@fruizg0302 El equipo de [Mr Jeff](https://github.com/MrJeffApp) sería muy feliz si se lanzará una versión publicada en Maven con los dos pull request propuestos.

**Comment by fruizg0302** [comment]
@blackleg A por ello entonces, deja lo pongo en el pipeline y lo revisamos hoy mismo. Sólo tengo una duda, te refieres al 91 y 78?

**Comment by blackleg** [comment]
A los dos pull request, 91 y 78.
El 91 es actual.
El 78 está mergeado en master, pero la version 2.2.1 no tiene ese cambio. Entiendo que esa version se creó desde código anterior al merge del 78.

**Comment by fruizg0302** [comment]
Vale, te damos update a través de este issue.

**Comment by blackleg** [comment]
Lo que tampoco me cuadra es que en master el groupId en el fichero pom.xml es `io.conekta` y version `2.1.7-SNAPSHOT` y en la nueva version del SDK publicada en maven sea groupId `com.conekta.library-java` y version `2.2.1`.

**Comment by fruizg0302** [comment]
Estoy seguro que esa es una omisión en la actualización. Tomo nota para que el pom.xml también se actualice.

**Comment by blackleg** [comment]
@fruizg0302 Gracias, si hay algún problema con el pull request no dudéis en comentarlo.

**Comment by fruizg0302** [comment]
@blackleg Seguro, si encuentras alguna otra cosa inconsistente avísanos y lo integramos en un fix para que se vaya todo en el siguiente release. Saludos

**Comment by fruizg0302** [comment]
@blackleg La liberación aún es work in progress de nuestro lado. Te avisamos en cuanto queden listas las revisiones. Aún no tengo un ETA, pero no debería demorarnos mucho.

**Comment by blackleg** [comment]
Gracias @fruizg0302 por el feedback

**Comment by blackleg** [comment]
@fruizg0302 Alguna novedad al respecto?

**Comment by matiasrosemberg** [comment]
This project is now deprecated; you can use the newer one: https://github.com/conekta/ct-conekta-java
