### ISSUE TITLE
Release order cancel method

### ISSUE THREAD

**Issue by hectorespert** [conekta/conekta-java#90]
@fruizg0302 @mariounderwood ¿Sería posible tener una nueva release que soporte el método para cancelar una autorización https://github.com/conekta/conekta-java/pull/78?

**Comment by leofischer** [comment]
@blackleg - sí, eso debería de existir.

**Comment by pedroxs** [comment]
While this repo is still abandoned and issues #88 and #78 are not officially released I recommend using the following workaround:

https://jitpack.io/#conekta/conekta-java/601360d6cc

It is possible to also extend the Order class with the desired method call but that is more cumbersome and harder to keep track / update, example:

```
import io.conekta.Error;
import io.conekta.ErrorList;
import io.conekta.Order;

public class OrderOverload extends Order {

    public void cancelPreAuth() throws ErrorList, Error {
        this.customAction("POST", "void", null);
    }
}
```

**Comment by DiegoValeConekta** [comment]
Hi @pedroxs, both solutions it proposes are viable today.

I also tell you that we are already working on improving our Conekta-Java repository so it will be more updated soon.

Thanks for contributing.

**Comment by matiasrosemberg** [comment]
This project is now deprecated; you can use the newer one: https://github.com/conekta/ct-conekta-java
